# Основные настройки сайта
title: GYM WORK
description: Премиальный тренажерный зал с современным оборудованием и профессиональными тренерами
baseurl: "" # подпапка, если сайт находится в поддиректории
url: "https://yourdomain.com" # ваш домен
email: info@gymwork.ru
phone: "+7 (123) 456-78-90"
address: "ул. Спортивная, 123, г. Москва"

# Настройки локализации
lang: ru
encoding: utf-8
timezone: Europe/Moscow

# Настройки сборки
markdown: kramdown
permalink: pretty

# Настройки Sass
sass:
  sass_dir: _sass
  style: compressed

# Настройки коллекций
collections:
  trainers:
    output: true
    permalink: /trainers/:path/

# Настройки SEO
defaults:
  - scope:
      path: ""
    values:
      layout: default
      author: GYM WORK Team

# Данные для навигации
navigation:
  - name: "О нас"
    url: "/#about"
  - name: "Оснащение"
    url: "/#facilities"
  - name: "Тренеры"
    url: "/#trainers"
  - name: "Галерея"
    url: "/#gallery"
  - name: "Контакты"
    url: "/#contact"
  - name: "Записаться"
    url: "/signup.html"
    class: "btn"

# Часы работы
opening_hours:
  weekdays: "Пн-Пт: 7:00 - 23:00"
  weekend: "Сб-Вс: 9:00 - 21:00"

# Социальные сети
social:
  - name: "Instagram"
    url: "#"
    icon: "instagram"
  - name: "Facebook"
    url: "#"
    icon: "facebook"
  - name: "YouTube"
    url: "#"
    icon: "youtube"
  - name: "Telegram"
    url: "#"
    icon: "telegram"

# Настройки плагинов
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Исключения из обработки
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - .gitignore